baseURL = 'https://VLDrenth.github.io/VLDrenth'
languageCode = 'en-us'
title = 'Random Learnings'
theme = 'PaperMod'

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true


[params.footer]
hidePowered = true
hideCopyright = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/VLDrenth"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "Tags"
identifier = "tags"
weight = 30
url = "/tags/"